const SHEETS = {
  PRODUCTS: "PRODUCTS",
  AGENTS: "AGENTS",
  AGENT_RATES: "AGENT_RATES",
  ORDERS: "ORDERS",
  ORDER_ITEMS: "ORDER_ITEMS",
  STOCK_MOVEMENT: "STOCK_MOVEMENT",
  USERS: "USERS",
  CONFIG: "CONFIG",
  BILLING: "BILLING"
};
