const SHEETS = {
  PRODUCTS: "PRODUCTS",
  AGENTS: "AGENTS",
  AGENT_RATES: "AGENT_RATES",
  AGENT_GROUP_RATES: "AGENT_GROUP_RATES",
  ORDERS: "ORDERS",
  ORDER_ITEMS: "ORDER_ITEMS",
  BACKUP_ORDERS: "BACKUP_ORDERS",
  BACKUP_ORDER_ITEMS: "BACKUP_ORDER_ITEMS",
  STOCK_MOVEMENT: "STOCK_MOVEMENT",
  USERS: "USERS",
  CONFIG: "CONFIG",
  TODAY_ORDERS: "TODAY_ORDERS",
  TODAY_ORDER_ITEMS: "TODAY_ORDER_ITEMS"
};

const AGENT_GROUP_OPTIONS = [
  "Super VIP",
  "VIP รวมส่ง",
  "VIP",
  "เรทคลินิก",
  "เรทตัวแทน",
  "ร้าน Fah",
  "ร้าน Nuwa skin"
];

const DEFAULT_AGENT_GROUP = "VIP รวมส่ง";
